server:
  port: 8082

spring:
  application:
    name: project-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hive_db
    username: hive_user
    password: hive_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: myVerySecretKeyForHiveApplication

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/hive_db

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
